#!/bin/bash
# ==========================================

cd /usr/bin
rm -rf restart &>/dev/null
rm -r restart &>/dev/null
rm restart &>/dev/null
rm -r sslh-fix-reboot &>/dev/null
rm -rf sslh-fix-reboot &>/dev/null
rm sslh-fix-reboot &>/dev/null
rm -r updatemenu &>/dev/null
rm -rf updatemenu &>/dev/null
rm updatemenu &>/dev/null
rm -r menu &>/dev/null
rm -rf menu &>/dev/null
rm updatemenu &>/dev/null

cd /usr/bin
wget -O sslh-fix-reboot "${psslh}/sslh-fix/sslh-fix-reboot.sh" &>/dev/null
wget -O restart "https://raw.githubusercontent.com/fisabiliyusri/Mantap/main/ssh/restart.sh" &>/dev/null
wget -O updatemenu "https://raw.githubusercontent.com/fisabiliyusri/Mantap/main/update/updatemenu.sh" &>/dev/null
wget -O menu "https://raw.githubusercontent.com/fisabiliyusri/Mantap/main/update/menu.sh" &>/dev/null

cd /usr/bin
chmod +x sslh-fix-reboot
chmod +x restart
chmod +x updatemenu
chmod +x menu

cd /root/
# nano /etc/rc.local
cat >/etc/rc.local <<-END
#!/bin/sh -e
# rc.local
# By default this script does nothing.

sslh-fix-reboot
screen -dmS badvpn badvpn-udpgw --listen-addr 127.0.0.1:7100 --max-clients 500
screen -dmS badvpn badvpn-udpgw --listen-addr 127.0.0.1:7200 --max-clients 500
screen -dmS badvpn badvpn-udpgw --listen-addr 127.0.0.1:7300 --max-clients 500
iptables -I INPUT -p udp --dport 5300 -j ACCEPT
iptables -t nat -I PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 5300
exit 0
END

# Ubah izin akses
chmod +x /etc/rc.local

# enable rc local
systemctl enable rc-local
systemctl start rc-local.service

# disable ipv6
echo 1 >/proc/sys/net/ipv6/conf/all/disable_ipv6
sed -i '$ i\echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6' /etc/rc.local

cd /root/
