#!/bin/bash

msg() {
  local colors="/etc/new-cr4r-color"
  if [[ ! -e $colors ]]; then
    COLOR[0]='\033[1;37m' #BRAN='\033[1;37m'
    COLOR[1]='\e[31m'     #VERMELHO='\e[31m'
    COLOR[2]='\e[32m'     #VERDE='\e[32m'
    COLOR[3]='\e[33m'     #AMARELO='\e[33m'
    COLOR[4]='\e[34m'     #AZUL='\e[34m'
    COLOR[5]='\e[35m'     #MAGENTA='\e[35m'
    COLOR[6]='\033[1;36m' #MAG='\033[1;36m'
  else
    local COL=0
    for number in $(cat $colors); do
      case $number in
      1) COLOR[$COL]='\033[1;37m' ;;
      2) COLOR[$COL]='\e[31m' ;;
      3) COLOR[$COL]='\e[32m' ;;
      4) COLOR[$COL]='\e[33m' ;;
      5) COLOR[$COL]='\e[34m' ;;
      6) COLOR[$COL]='\e[35m' ;;
      7) COLOR[$COL]='\033[1;36m' ;;
      esac
      let COL++
    done
  fi
  NEGRITO='\e[1m'
  SEMCOR='\e[0m'
  cor="${COLOR[4]}————————————————————"
  garis=${SEMCOR}${cor}${SEMCOR}
  case $1 in
  -ne) cor="${COLOR[1]}${NEGRITO}" && echo -ne "${cor}${2}${SEMCOR}" ;;
  -org) cor="${COLOR[3]}${NEGRITO}" && echo -e "${cor}${2}${SEMCOR}" ;;
  -warn) cor="${COLOR[3]}${NEGRITO}[!] ${COLOR[1]}" && echo -e "${cor}${2}${SEMCOR}" ;;
  -red) cor="${COLOR[1]}${NEGRITO}" && echo -e "${cor}${2}${SEMCOR}" ;;
  -gr) cor="${COLOR[6]}${NEGRITO}" && echo -e "${cor}${2}${SEMCOR}" ;;
  -bra) cor="${COLOR[0]}${NEGRITO}" && echo -e "${cor}${2}${SEMCOR}" ;;
  -line) echo -e "${garis}${2}${garis}" ;;
  esac
}

inst_comp() {
  msg -org "Menginstall $1"
  [[ $(dpkg --get-selections | grep -w "$1" | head -1) ]] || apt-get install $1 -y &>/dev/null
  tput cuu1 && tput dl1
}

persen() {
  printf %.2f%% "$((10 ** 6 * $@))e-4"
}

pause() {
  msg -red "Tekan Enter Untuk melanjutkan" && read Enter && tput cuu1 && tput cuu1
}

kill_port() {
  lsof -t -i tcp:$1 -s tcp:listen | sudo xargs kill
}

install_all_component() {
  plugin=$1
  totalPLugin=$(wc -l <<<$plugin)
  if [[ $totalPLugin == 0 ]]; then
    msg -red "Tidak ada plugin yang di install"
  else
    msg -warn "${totalPLugin} plugin yang akan di install"
    numm=1
    for abc in $plugin; do
      if [[ $abc != "" ]]; then
        prsn=$(persen $numm/$totalPLugin)
        msg -red "Proses Instalasi ${prsn}"
        inst_comp $abc
        let numm++
        tput cuu1 && tput cuu1
      fi
    done
    msg -gr "${totalPLugin} plugin yang akan di install [Selesai]"
  fi
}

hapus_target() {
  msg -warn "Menghapus $1"
  systemctl stop $1 &>/dev/null
  systemctl disable $1 &>/dev/null

  apt --purge remove *$1* -y &>/dev/null
  apt autoremove -y &>/dev/null

  rm -rf $(whereis $1) &>/dev/null
  find /etc/ -name "*${1}*" -delete &>/dev/null
  find /usr/bin/ -name "*${1}*" -delete &>/dev/null
  find /usr/local/bin/ -name "*${1}*" -delete &>/dev/null
  find /etc/init.d -name "*${1}*" -delete &>/dev/null
  find /etc/systemd/system -name "*${1}*" -delete &>/dev/null
  find /var/log/ -name "*${1}*" -delete &>/dev/null
}

hapus_ssh() {
  hapus_target dropbear
  hapus_target badvpn-udpgw
  hapus_target sslh
}

hapus_xray() {
  hapus_target xray
  hapus_target xlts-xray
  hapus_target vless
  hapus_target vmess
  hapus_target grpc
  hapus_target nsdomain
  hapus_target domain

  hapus_target v2ray
  hapus_target client-sldns
  hapus_target server-sldns

  hapus_target slowdns
  rm -rf /var/lib/crot/ipvps.conf &>/dev/null
}

hapus_trojango() {
  hapus_target trojan-go
  hapus_target trojango
}

hapus_tool() {
  rm -rf /root/LogServerVPN &>/dev/null
  hapus_target sstp
  hapus_target l2tp
  hapus_target pptp
  hapus_target addss
  hapus_target sstp
  hapus_target ssr
  hapus_target addwg
  hapus_target vnstat
  hapus_ssh
  hapus_xray
  hapus_trojango

  ### Nginx port
  rm -rf /etc/nginx/sites-enabled/port80.conf /home/vps/ &>/dev/null
}

tanya() {
  read -p "$(msg -ne '$1 => ')" $2
}

### Export Function
export -f msg
export -f inst_comp
export -f persen
export -f pause
export -f install_all_component
export -f hapus_tool
export -f hapus_ssh
export -f hapus_xray
export -f hapus_trojango
export -f tanya

### Export Variabel
export HomeRepo="/root/ServerVPN"
export rawRepo="https://raw.githubusercontent.com/cr4r/ServerVPN/main"
export dir_slh="/etc/slowdns"
export dir_v2ray="/etc/v2ray"
export dir_xray="/etc/xray"
export home="/root/LogServerVPN"

export IP=$(curl -Ls http://ipinfo.io/ip)
export urlFile="https://raw.githubusercontent.com/cr4r/ServerVPN"
export NET=$(ip -o $ANU -4 route show to default | awk '{print $5}')

### link tools
export pssh="${rawRepo}/ssh"
export psstp="${rawRepo}/sstp"
export pssr="${rawRepo}/ssr"
export psocks="${rawRepo}/shadowsocks"
export pwrguard="${rawRepo}/wireguard"
export pxray="${rawRepo}/xray"
export pipsec="${rawRepo}/ipsec"
export pbackup="${rawRepo}/backup"
export pwst="${rawRepo}/websocket"
export pohp="${rawRepo}/ohp"
export ptrojango="${rawRepo}/trojango"
export pstunnel5="${rawRepo}/stunnel5"
export psldns="${rawRepo}/SLDNS"
export psslh="${rawRepo}/sslh-fix"

### Jika ingin run function secara langsung
$1
