#!/bin/bash

msg() {
  local colors="/etc/new-cr4r-color"
  if [[ ! -e $colors ]]; then
    COLOR[0]='\033[1;37m' #BRAN='\033[1;37m'
    COLOR[1]='\e[31m'     #VERMELHO='\e[31m'
    COLOR[2]='\e[32m'     #VERDE='\e[32m'
    COLOR[3]='\e[33m'     #AMARELO='\e[33m'
    COLOR[4]='\e[34m'     #AZUL='\e[34m'
    COLOR[5]='\e[35m'     #MAGENTA='\e[35m'
    COLOR[6]='\033[1;36m' #MAG='\033[1;36m'
  else
    local COL=0
    for number in $(cat $colors); do
      case $number in
      1) COLOR[$COL]='\033[1;37m' ;;
      2) COLOR[$COL]='\e[31m' ;;
      3) COLOR[$COL]='\e[32m' ;;
      4) COLOR[$COL]='\e[33m' ;;
      5) COLOR[$COL]='\e[34m' ;;
      6) COLOR[$COL]='\e[35m' ;;
      7) COLOR[$COL]='\033[1;36m' ;;
      esac
      let COL++
    done
  fi
  NEGRITO='\e[1m'
  SEMCOR='\e[0m'
  cor="${COLOR[4]}————————————————————"
  garis=${SEMCOR}${cor}${SEMCOR}
  case $1 in
  -ne) cor="${COLOR[1]}${NEGRITO}" && echo -ne "${cor}${2}${SEMCOR}" ;;
  -org) cor="${COLOR[3]}${NEGRITO}" && echo -e "${cor}${2}${SEMCOR}" ;;
  -warn) cor="${COLOR[3]}${NEGRITO}[!] ${COLOR[1]}" && echo -e "${cor}${2}${SEMCOR}" ;;
  -red) cor="${COLOR[1]}${NEGRITO}" && echo -e "${cor}${2}${SEMCOR}" ;;
  -gr) cor="${COLOR[6]}${NEGRITO}" && echo -e "${cor}${2}${SEMCOR}" ;;
  -bra) cor="${COLOR[0]}${NEGRITO}" && echo -e "${cor}${2}${SEMCOR}" ;;
  -line) echo -e "${garis}${2}${garis}" ;;
  esac
}

inst_comp() {
  msg -org "Menginstall $1"
  [[ $(dpkg --get-selections | grep -w "$1" | head -1) ]] || apt-get install $1 -y &>/dev/null
  tput cuu1 && tput dl1
}

persen() {
  printf %.2f%% "$((10 ** 6 * $@))e-4"
}

pause() {
  msg -red "Tekan Enter Untuk melanjutkan" && read Enter && tput cuu1 && tput cuu1
}

kill_port() {
  lsof -t -i tcp:$1 -s tcp:listen | sudo xargs kill
}

install_all_component() {
  plugin=$1
  totalPLugin=$(wc -l <<<$plugin)
  msg -warn "${totalPLugin} plugin yang akan di install"
  numm=1
  for abc in $plugin; do
    prsn=$(persen $numm/$totalPLugin)
    msg -red "Proses Instalasi ${prsn}"
    inst_comp $abc
    let numm++

    tput cuu1 && tput cuu1
  done
  msg -gr "${totalPLugin} plugin yang akan di install [Selesai]"
}

hapus_tool() {
  ### SLHost
  rm -rf /root/domain /etc/v2ray/domain /etc/xray/domain /etc/xray/domain /root/nsdomain /var/lib/crot/ipvps.conf /root/nsdomain /root/domain &>/dev/null
  rm -rf /usr/bin/xray /usr/bin/v2ray /etc/xray /etc/v2ray /etc/v2ray/domain /root/nsdomain /etc/xray/domain /var/lib/crot/ipvps.conf &>/dev/null

  ### XRAY
  rm -rf /usr/bin/xray /etc/xray /var/log/xray/ /usr/local/bin/xray &>/dev/null
  rm /etc/systemd/system/xray.service /etc/systemd/system/trojan-go.service &>/dev/null
  systemctl disable xray.service &>/dev/null
  systemctl stop xray.service &>/dev/null

  ### Trojan-GO
  rm -rf /usr/bin/trojan-go /etc/trojan-go /usr/local/bin/trojan-go /var/log/trojan-go/ &>/dev/null
  systemctl disable trojan-go.service &>/dev/null
  systemctl stop trojan-go.service &>/dev/null

  ### Nginx port
  rm /etc/nginx/sites-enabled/port80.conf &>/dev/null

}

### Export Function
export -f msg
export -f inst_comp
export -f persen
export -f pause
export -f install_all_component
export -f hapus_tool
### Export Variabel
export IP=$(curl -Ls http://ipinfo.io/ip)
export HomeRepo="/root/ServerVPN"
